GET http://localhost:3000/api/wilder

###
POST http://localhost:3000/api/wilder
content-type: application/json

{
    "name": "Jane Doe"
}

###
PUT http://localhost:3000/api/wilder/4
content-type: application/json

{
    "name": "John Doe"
}

###
DELETE http://localhost:3000/api/wilder/4
content-type: application/json

{
    "name": "Jane Doe"
}

###
POST http://localhost:3000/api/wilder/2/skill
content-type: application/json

{
    "id": 3
}